llm-chat-completion:
  observations:
  - {batch_size: 1, cpu: 0, memory: 16778 MiB, perf: 85.31, time: 1764183940}
txt-to-image-gpus:
  observations:
  - {batch_size: 1, cpu: 0, memory: 33826 MiB, perf: 8.89, time: 1764183453}
  - {batch_size: 2, cpu: 0, memory: 33968 MiB, perf: 12.77, time: 1764186600}
  - {batch_size: 4, cpu: 0, memory: 34674 MiB, perf: 13.66, time: 1764188014}
  - {batch_size: 8, cpu: 0, memory: 36304 MiB, perf: 14.04, time: 1764189480}
  - {batch_size: 16, cpu: 0, memory: 39128 MiB, perf: 14.6, time: 1764191013}
  - {batch_size: 32, cpu: 0, memory: 44710 MiB, perf: 14.84, time: 1764192724}
  - {batch_size: 64, cpu: 0, memory: 55936 MiB, perf: 15.06, time: 1764195907}
version: 2.0
whisper-transcribe-single:
  observations:
  - {batch_size: 1, cpu: 0, memory: 4780 MiB, perf: 0.9, time: 1764185692}
  - {batch_size: 2, cpu: 0, memory: 5172 MiB, perf: 1.47, time: 1764186523}
  - {batch_size: 4, cpu: 0, memory: 5644 MiB, perf: 2.5, time: 1764187925}
  - {batch_size: 8, cpu: 0, memory: 6624 MiB, perf: 4.35, time: 1764189362}
  - {batch_size: 16, cpu: 0, memory: 8738 MiB, perf: 7.18, time: 1764190842}
  - {batch_size: 32, cpu: 0, memory: 12866 MiB, perf: 10.11, time: 1764183383}
  - {batch_size: 32, cpu: 0, memory: 12866 MiB, perf: 10.04, time: 1764192445}
  - {batch_size: 64, cpu: 0, memory: 21444 MiB, perf: 13.65, time: 1764195413}
  - {batch_size: 128, cpu: 0, memory: 39798 MiB, perf: 14.8, time: 1764198992}
