include:
  - all.yaml






# fp8:
#   inherits: _flops

#   argv:
#     --number: 30
#     --repeat: 90
#     --m: 16384
#     --n: 16384
#     --dtype: fp8

# fp16:
#   inherits: _flops

#   argv:
#     --number: 30
#     --repeat: 90
#     --m: 16384
#     --n: 16384
#     --dtype: fp16

# bf16:
#   inherits: _flops
 
#   argv:
#     --m: 16384
#     --n: 16384
#     --dtype: bf16

# tf32:
#   inherits: _flops
 
#   argv:
#     --m: 16384
#     --n: 16384
#     --dtype: fp32
#     --tf32: true

# fp32:
#   inherits: _flops
#   enabled: true
 
#   argv:
#     --m: 16384
#     --n: 16384
#     --dtype: fp32  