defaults: &defaults
  dirs:
    code: code/{name}
    venv: venv/{name}
    data: data
    runs: runs

  venv:
    type: virtualenv

  plan:
    method: per_gpu

  voir:
    --stop: 10
    --forward:
      - "#stdout"
      - "#stderr"
      - "#end"
      - loss
      - compute_rate
      - train_rate
      - loading_rate
      - gpudata
      - descr
      - progress
      - total
    --train-rate: true
    --poll-gpu: 5

resnet18: &resnet18
  <<<: *defaults
  definition: ../benchmarks/torchvision
  dirs:
    venv: venv/torchvision
  argv:
    --model: resnet18
    --with-amp: true
    --fixed-batch: true
    --lr: 0.1

benchmarks:
  r18-32:
    <<<: *resnet18
    argv:
      --batch-size: 16

  r18-64:
    <<<: *resnet18
    argv:
      --batch-size: 32
