system:
  # Nodes list
  nodes:
      # Alias used to reference the node
    - name: manager
      # Use 1.1.1.1 as an ip placeholder
      ip: 1.1.1.1
      # Use this node as the master node or not
      main: true
      # User to use in remote milabench operations
      user: user

  # Cloud instances profiles
  cloud_profiles:
    azure:
      username: ubuntu
      size: Standard_B2ats_v2
      location: eastus2
    ec2:
      username: ubuntu
      instance_type: t2.micro
      volume_size: 8
      region: us-east-2
